### ISSUE TITLE
Task List - First Half

### ISSUE THREAD

**Issue by LydianMaster** [LydianMaster/ASD-SD#1]
- [x]  Setup a github for your class work
- [x] Create a list of tasks in your github that matches this list
- [x] Put one of your own projects in the github (any prototype you've made is fine, your main portfolio project is fine if you have one)
- [x] Learn the basic defintions of agile/scrum
- [ ] Run an agile/scrum style meeting at one class this quarter
- [x] Learn the basics of a distributed or cloud build
- [ ] Explain the basics of a distributed or cloud build process to the class
- [ ] [Extra credit] Setup a distributed or cloud build process for your project
