### ISSUE TITLE
Task List - Second Half

### ISSUE THREAD

**Issue by LydianMaster** [LydianMaster/ASD-SD#2]
- [ ] [Extra credit] Automate your build process so that it happens weekly
- [ ] Setup a Discord channel for your project and invite everyone else in the class
- [ ] Add a "tool" using C# to Unity Editor (the tool can be purely visual and non-functional -- it should be related to your project)
- [x] Write a definition of "unit tests" and email it to me
- [ ] Create a single unit test for your project
- [x] Learn the definition of man-month and estimate the man month production cost of taking your project to a "full and complete prototype"
- [x] Identify an area of computer engineering you feel you need more understanding of and tell me. We will go into more detail on this area.
- [x] Put all of these tasks in Github in your project and assign them to yourself.
- [ ] Add me to your Github project and give me the necessary permissions to view everything.
- [x] [Optional] Add the other students to your Github project
